name: aoc-copilot tests

on:
  pull_request:
    branches: [ main ]

env:
  AOC_SESSION_COOKIE: ${{ secrets.AOC_SESSION_COOKIE }}
  LOCALAPPDATA: ${{ vars.LOCALAPPDATA }}

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Checkout examples
        uses: actions/checkout@v4
        with:
          repository: "jasonmuzzy/aoc-copilot-examples"
          token: ${{ secrets.AOC_EXAMPLE_TOKEN }}
          path: "examples"

      - name: Remove all except 4-digit year folders and their contents
        run: |
          # Navigate to the examples directory
          cd examples

          # Find and delete all directories except those named with exactly 4 digits
          find . -mindepth 1 -type d ! -name '[0-9][0-9][0-9][0-9]' -exec rm -rf {} +

          # Find and delete all files not under the 4-digit year directories
          find . -mindepth 1 -type f -not -path './[0-9][0-9][0-9][0-9]/*' -exec rm -f {} +

      - name: Cache config
        uses: actions/cache@v3
        with:
          key: aoc-copilot-cache
          path: ${{ vars.LOCALAPPDATA }}

      - run: mkdir -p ${{ vars.LOCALAPPDATA }}
      - run: ls -lR ${{ vars.LOCALAPPDATA }}

      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci
      - run: npm run test
      - run: npm run build
